name: Ocenjevanje naloge

on:
  push:
    branches: [main]

jobs:
  Ocenjevanje-naloge:
    name: Ocenjevanje naloge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Namesti potrebne knjižnice
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pokaži odgovore študenta
        run: |
          echo "Vsebina odgovori.json:"
          cat odgovori.json || echo "Datoteka manjka!"
          cp odgovori.json results.json

      - name: Pretvori notebook v Python datoteko
        run: |
          jupyter nbconvert --to python PreverjanjeZnanja.ipynb --output=student_code.py
          cat student_code.py

      - name: Prenesi skrite teste
        run: |
          curl -o tests.py https://raw.githubusercontent.com/lhrs-workshops/noo-tests/refs/heads/main/test_template.py

      - name: Zazeni vse teste
        run: pytest tests.py --disable-warnings -v
        continue-on-error: true

      - name: Prikaži rezultate
        run: |
          echo "Pregled rezultatov:"
          if [ ! -f grade_summary.json ]; then
            echo "Napaka: Datoteka 'grade_summary.json' ne obstaja."
            exit 1
          fi

          total=$(jq '.max_score' grade_summary.json)
          passed=$(jq '.total_score' grade_summary.json)

          echo "✅ Skupaj testov: $total"
          echo "🟢 Uspešno opravljenih: $passed"
          echo "🔴 Neuspešnih: $((total - passed))"

          echo ""
          echo "📋 Neuspešni testi:"
          jq -r '.breakdown | to_entries[] | select(.value==false) | "- " + .key' grade_summary.json || echo "✔️  Vsi testi so uspešni."

      - name: Nalozi rezultate (grade_summary.json)
        uses: actions/upload-artifact@v4
        with:
          name: grade-summary
          path: grade_summary.json
